services:
###> doctrine/doctrine-bundle ###
  database:
    image: mysql:8.0.30
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: web-admin
    volumes:
      - mysql-data:/var/lib/mysql
###< doctrine/doctrine-bundle ###
volumes:
  mysql-data:
    # driver: local